server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: backend
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture
    username: yrd
    password: yrdml980
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #only development environment enable log
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # default 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: "api document"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yrd.backend.controller